### ISSUE TITLE
Add some readme

### ISSUE THREAD

**Issue by doubleTroub1e** [ducthanh98/airdrop#1]
Hi,  your code is really good and with the little help of chat GPT I've started bump and gemz tappers which is amazing! but having some issues starting oxygen- minter
Could you please add some readme with short steps and which info is needed? also, ifpossible same dockerfile for oxygen as for gemz?

**Comment by doubleTroub1e** [comment]
@ducthanh98 also. if possible, could you please add some example of config files needed for projects, like quackquack require <conf.toml> file but I have no idea what should be there and structure of file also

**Comment by ducthanh98** [comment]
Hi @doubleTroub1e 
I added example config file for quackquack.  Regarding oxygen, I haven't finished that yet. I don't think anyone will see this repository, lol. I will notify you when I have finished it.

**Comment by doubleTroub1e** [comment]
haha, thanks)) I was searching by URL of coin I'm interested in. still can't find some.
found [clayton](https://t.me/claytoncoinbot/game?startapp=974565
), but it is not working( and [simple tap](https://t.me/Simple_Tap_Bot?start=1716824326795) can't find at all, same for [MTK mafia clicker](https://t.me/mtkbossbot?start=ref595909481)

**Comment by ducthanh98** [comment]
@doubleTroub1e updated for clayton

**Comment by doubleTroub1e** [comment]
wow, thanks a lot, will start it today!
