### ISSUE TITLE
New farming available

### ISSUE THREAD

**Issue by doubleTroub1e** [ducthanh98/airdrop#16]
Hi again, today found new farming tool called DAWN Validator
https://chromewebstore.google.com/detail/dawn-validator-chrome-ext/fpdkjdnhkakefebpekbdhillbhonfjjp

similar to GRASS/NODEPAY, probably won't be that hard to add it to your tools as should be same approach as for GRASS

during registration you could use my ref code: j4rro2

and yes, ref code should be entered manually, not that convenient

**Comment by doubleTroub1e** [comment]
also, there is a game which does confirm airdrop in the end of September, there is already tapper for it, but there is no auto purchase of improvements 
game X empire -> https://t.me/muskempire_bot/game?startapp=hero595909481

**Comment by ducthanh98** [comment]
Done
