### ISSUE TITLE
gemz stopped working

### ISSUE THREAD

**Issue by doubleTroub1e** [ducthanh98/airdrop#6]
since today I've faced issue with running gemz
error I have
```
gemz  | Lỗi rồi:
gemz  | Đã chạy hết các query. Nghỉ 5 phút trước khi tiếp tục...
``` 
can you please check once have time?

**Comment by ducthanh98** [comment]
It sounds like your token has expired. Try to get new token from web. I haven't found a way to retrieve the Infinity token.

**Comment by doubleTroub1e** [comment]
I've tried that already, this is not a token issue, before it was token issue then error was "unauthorized" and simple token update helped that time, but now there is no error showed and just not working.
I've start proxy/no proxy versions - same results

**Comment by ducthanh98** [comment]
Fixed.
Gemz changed their url

**Comment by doubleTroub1e** [comment]
thanks! 
working fine now
