### ISSUE TITLE
Gemz - Token expired

### ISSUE THREAD

**Issue by TemoSulava** [ducthanh98/airdrop#7]
![image](https://github.com/ducthanh98/airdrop/assets/72650579/3db5689f-1467-4f3c-bbfe-f7360cc1deee)

**Comment by TemoSulava** [comment]
Fixed it, just the api has changed version!

**Comment by doubleTroub1e** [comment]
if you've fix that - can you create a PR here so that everything have up to date version, and so that author won't do same job again?

**Comment by doubleTroub1e** [comment]
btw, question to both, how did you get right headers initially if app can be started only on phone? I mean I can open devtools in browser and check there, but if app doesn't want to start there, then how to start to get correct requests?

**Comment by TemoSulava** [comment]
> btw, question to both, how did you get right headers initially if app can be started only on phone? I mean I can open devtools in browser and check there, but if app doesn't want to start there, then how to start to get correct requests?

You enable developer mode on your phone and see the http requests going through when you do actions on the game through the phone
