### ISSUE TITLE
GRASS/Nodepay setup

### ISSUE THREAD

**Issue by doubleTroub1e** [ducthanh98/airdrop#8]
Hey can you please add sample config file for nodepay and update for grass for proxy setup, should it have same device ID for every proxy?

**Comment by doubleTroub1e** [comment]
@ducthanh98  can you please help here?

**Comment by ducthanh98** [comment]
Added config example.  I create devices automatically so you just need a list of proxy and your token (Nodepay)
I hope you can support me with a reference:  https://app.nodepay.ai/register?ref=TF2dZU9xE625uNe

**Comment by ducthanh98** [comment]
Although grass code supports proxy but I can run it only on my home wifi. They perform a strict check on IP addresses so I can't test it

**Comment by doubleTroub1e** [comment]
I was already registered, but can recommend you this [site](https://www.webshare.io/?referral_code=rrajfg22cbrq) - it does give you 10 residential proxy for free - 1GB/month, they could change time to time but you can  create API key and extract them via API on weekly basis. multi ACC won't work but nodepay point are adding

**Comment by ducthanh98** [comment]
Have you tried this site for grass?

**Comment by doubleTroub1e** [comment]
yes, but 1 gb is not enough for month for nodepay., but does enough for grass, it was working some time ago, but later stopped working

**Comment by Customimine** [comment]
Grass working with sock5://username:password@ip:port. Not http or https. Please try to test it. With Grass must same Device ID for every proxy. nodepay no need, can different @doubleTroub1e

**Comment by doubleTroub1e** [comment]
@ducthanh98  I can confirm that Grass is working fine with socks5 proxy, you can check with that free websahre proxy I've sent before

**Comment by ducthanh98** [comment]
I am currently using code to deploy on my VPS in Vietnam, and it worked. I think the problem here is the trustworthiness of the IP.

**Comment by luongtu996** [comment]
chào thanh. bạn cho mình hỏi b thuê vps bên nào với cấu hình như nào thế. mình định setup mà chưa biết bên nào giá cả ok

**Comment by Customimine** [comment]
Vsis cũng được, hoặc contabo
